services:
  app:
    build: .
    volumes:
      - .:/webapp
    ports:
      - 8000:8000
    image: app:webapp
    container_name: webapp_mysite_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./database/db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=mysitedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql