services:

  # Django WSGI for Gunicorn
  wsgi_app:
    container_name: mysite_wsgi
    build:
      context: ./mysite
    volumes:
      - mysite:/webapp
    ports:
      - "8000:8000"
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
      - redis

  # Django ASGI for Daphne
  asgi_app:
    container_name: mysite_asgi
    build:
      context: ./mysite
    volumes:
      - mysite:/webapp
    ports:
       - "8001:8001"
    command: daphne -b 0.0.0.0 -p 8001 mysite.asgi:application
    depends_on:
      - db
      - redis
      - wsgi_app

  # Database postgres
  db:
    container_name: postgres_db
    image: postgres
    volumes:
      - mysitedb:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=mysitedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql

  # Redis
  redis:
    container_name: redis
    image: redis:alpine

  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - mysite:/webapp
    depends_on:
      - wsgi_app
      - asgi_app

volumes:
  mysite:
  mysitedb:
