services:

  # Django WSGI and ASGI App
  django_app:
    container_name: django_app
    build:
      context: ./mysite
    volumes:
      - ./mysite:/webapp
    ports:
      - "8000:8000"
      - "8001:8001"
    command: sh -c "gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 & daphne -b 0.0.0.0 -p 8001 mysite.asgi:application"
    depends_on:
      - db
      - redis

  # Database postgres
  db:
    container_name: postgres_db
    image: postgres
    volumes:
      - mysitedb:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=mysitedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql

  # Redis
  redis:
    container_name: redis
    image: redis:alpine

  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./mysite:/webapp
    depends_on:
      - django_app

volumes:
  mysitedb:
