# Generated by Django 4.1.7 on 2023-07-01 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_user_address_user_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
